language: node_js
node_js:
  - "8"
script:
 - echo "Deploying to firebase!!"
install:
  - npm install -g firebase-tools
  - npm install eslint --save-dev
  - npm --init
after_success:
  - firebase deploy --project cv-proj-5b862 --token $FIREBASE_TOKEN
