language: node_js
node_js:
  - "12"
script:
 - echo "Deploying to firebase!!"
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project cv-proj-5b862 --token $FIREBASE_TOKEN
