version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm install -g firebase-tools
            - firebase deploy --project cv-proj-5b862 --token $FIREBASE_TOKEN
workflows:
    build-and-test:
      jobs:
        - build-and-test