# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        # App id can be found on the General Settings page
        appId: cv-proj-5b862
        # Upload token - see Firebase CLI Reference
        token: 1//09Af3cCH--IIgCgYIARAAGAkSNwF-L9Irfu4nY7tYE7zeclpGzR--kjeU_AsTJrXw1qUk3fZbqhqswV_1m1i2eB3HL6WZZlh6lB8
        # Artifact to upload (.apk or .ipa)
        file: public
        # Distribution groups
        groups: # optional
        # Release notes visible on release page
        releaseNotes: # optional
        # Release notes visible on release page
        releaseNotesFile: # optional
        # Flag that can included to print verbose log output.
        debug: # optional
